[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dflash"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["dflash*"]
where = ["."]
